Added projects page with styling
cyu6/step-portfolio pull request #3
Opened 2020-06-24 15:48 UTC by cyu6

2020-06-24 18:02 UTC, paulaksp requested changes
Include screenshot(s) for any UI related PRs.

2020-06-24 18:02 UTC, paulaksp commented on portfolio/src/main/webapp/style.css
> +#projectscontent {
formatting, use two spaces for css generally preferred than four.

2020-06-24 18:02 UTC, paulaksp commented on portfolio/src/main/webapp/projects.html
> +            <li>MIT Beat the Pandemic II Wireframe:</li>
nit: is there additional things after the ':' that is meant to be there?

2020-06-24 18:02 UTC, paulaksp commented on portfolio/src/main/webapp/projects.html
> +    </div>
overkill comment for this starter project, but just as an fyi
-- navbar isn't reusable even though i assume you'll be using the same div in all the various pages. so changing the navbar requires changing each of this replica in all the pages.

later for the capstone or more complicated front-end, having some form of templating (either through importing the HTML, or through some framework like React, etc).

again, no need to act on this but just a random note.

2020-06-24 18:09 UTC, cyu6 commented
![projects](https://user-images.githubusercontent.com/39574893/85609716-59ce6d80-b624-11ea-9e65-e545d350300c.png)

2020-06-24 18:10 UTC, cyu6 commented on portfolio/src/main/webapp/projects.html
> +            <li>MIT Beat the Pandemic II Wireframe:</li>
Yup I just didn't look up the links for what I wanted to attach yet so they're like placeholders for now

2020-06-25 00:14 UTC, paulaksp approved these changes
Generally LGTM.

Some of the css might need to change in future PRs depending on whether you want things to be responsive, or how you'd like things to look at with various screen-sizes, etc but we can discuss the styling part of it separate from the PR depending on your requirements and thresholds for how to get things to look a certain way.

2020-06-25 00:14 UTC, paulaksp commented on portfolio/src/main/webapp/style.css
> +#projectscontent {
nit: use dashes/hypens to concatenate words for css selectors
https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

2020-06-25 00:14 UTC, paulaksp commented on portfolio/src/main/webapp/style.css
> +  border-color: lightcoral;
nit: generally prefer hex colors compared to the name colors (ie lightcoral = `#f08080`), assuming that there will be more colors being used across codebase, some of the hex-colors not having a corresponding name.

2020-06-25 14:14 UTC, cyu6 commented
The main commit is ae5a74f - I tried rebasing on another branch and ended up duplicating the commits (oops)

2020-06-25 15:32 UTC, paulaksp approved these changes
Wasn't really sure what you meant by the duplicating commits, but LGTM.

2020-06-26 15:14 UTC, merged